export const PERMISSIONS = {
  PROFILE: {
    READ: 'profile.read',
    UPDATE: 'profile.update',
  },
  USERS: {
    READ: 'users.read',
    CREATE: {
      DEFAULT: 'users.create.deafault',
      WITH_ROLE: 'users.create.with-role',
    },
    UPDATE: 'users.update',
    DELETE: 'users.delete',
  },
  CLIENTS: {
    READ: 'clients.create',
    CREATE: 'clients.read',
    UPDATE: 'clients.update',
    DELETE: 'clients.delete',
  },
  ACCOUNTS: {
    READ: 'accounts.create',
    CREATE: 'accounts.read',
    UPDATE: 'accounts.update',
    DELETE: 'accounts.delete',
  },
  ASSIGNATIONS: {
    READ: 'assignations.create',
    CREATE: 'assignations.read',
    UPDATE: 'assignations.update',
  },
  LOGS: {
    READ: 'logs.read',
  },
  ROLES: {
    READ: 'roles.read',
  },
  ENGLISH_LEVELS: {
    READ: 'english-levels.read',
  },
};

export const PERMISSIONS_ARRAY = [
  PERMISSIONS.PROFILE.READ,
  PERMISSIONS.PROFILE.UPDATE,
  PERMISSIONS.USERS.READ,
  PERMISSIONS.USERS.CREATE.DEFAULT,
  PERMISSIONS.USERS.CREATE.WITH_ROLE,
  PERMISSIONS.USERS.UPDATE,
  PERMISSIONS.USERS.DELETE,
  PERMISSIONS.CLIENTS.READ,
  PERMISSIONS.CLIENTS.CREATE,
  PERMISSIONS.CLIENTS.UPDATE,
  PERMISSIONS.CLIENTS.DELETE,
  PERMISSIONS.ACCOUNTS.READ,
  PERMISSIONS.ACCOUNTS.CREATE,
  PERMISSIONS.ACCOUNTS.UPDATE,
  PERMISSIONS.ACCOUNTS.DELETE,
  PERMISSIONS.ASSIGNATIONS.READ,
  PERMISSIONS.ASSIGNATIONS.CREATE,
  PERMISSIONS.ASSIGNATIONS.UPDATE,
  PERMISSIONS.LOGS.READ,
  PERMISSIONS.ROLES.READ,
  PERMISSIONS.ENGLISH_LEVELS.READ,
];

export const ROLES = {
  default: [
    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,
    PERMISSIONS.ENGLISH_LEVELS.READ,
  ],
  admmin: [
    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,
    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.CREATE.DEFAULT,
    PERMISSIONS.USERS.UPDATE,
    PERMISSIONS.USERS.DELETE,
    PERMISSIONS.CLIENTS.READ,
    PERMISSIONS.CLIENTS.CREATE,
    PERMISSIONS.CLIENTS.UPDATE,
    PERMISSIONS.CLIENTS.DELETE,
    PERMISSIONS.ACCOUNTS.READ,
    PERMISSIONS.ACCOUNTS.CREATE,
    PERMISSIONS.ACCOUNTS.UPDATE,
    PERMISSIONS.ACCOUNTS.DELETE,
    PERMISSIONS.ASSIGNATIONS.READ,
    PERMISSIONS.ASSIGNATIONS.CREATE,
    PERMISSIONS.ASSIGNATIONS.UPDATE,
    PERMISSIONS.LOGS.READ,
    PERMISSIONS.ROLES.READ,
    PERMISSIONS.ENGLISH_LEVELS.READ,
  ],
  superAdmin: [...PERMISSIONS_ARRAY],
};
